language: python

matrix:
  include:
    - name: "Python 3.7 on Xenial Linux"
      os: linux
      dist: xenial
      python: 3.7
    - name: "Python 3.6 on Xenial Linux"
      os: linux
      dist: xenial
      python: 3.6
    - name: "Python 3.5 on Xenial Linux"
      os: linux
      dist: xenial
      python: 3.5
    - name: "Python 3.7.4 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.4
        - python -m pip install --upgrade pip
        - python --version ; pip --version; pip list
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    # Note: windows builds are in early access stage.
    - name: "Python 3.6.8 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.8
        - python -m pip install --upgrade pip
        - python --version ; pip --version; pip list
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.5.4 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.5.4
        - python -m pip install --upgrade pip
        - python --version ; pip --version; pip list
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11
      language: shell
      before_install:
        - eval "$(pyenv init -)";
        - lastest_ver=$(pyenv install --list | grep 3.7 | grep -E "^\s{2}\d+\.\d+\.\d+" | tail -1)
        - which -a $lastest_ver || (pyenv install $lastest_ver; pyenv global $lastest_ver)
        - python --version ; pip --version ; sw_vers; pip list
    - name: "Python 3.6 on macOS"
      os: osx
      osx_image: xcode11
      language: shell
      before_install:
        - eval "$(pyenv init -)";
        - lastest_ver=$(pyenv install --list | grep 3.6 | grep -E "^\s{2}\d+\.\d+\.\d+" | tail -1)
        - which -a $lastest_ver || (pyenv install $lastest_ver; pyenv global $lastest_ver)
        - python --version ; pip --version ; sw_vers; pip list
    - name: "Python 3.5 on macOS"
      os: osx
      osx_image: xcode11
      language: shell
      before_install:
        - eval "$(pyenv init -)";
        - lastest_ver=$(pyenv install --list | grep 3.5 | grep -E "^\s{2}\d+\.\d+\.\d+" | tail -1)
        - which -a $lastest_ver || (pyenv install $lastest_ver; pyenv global $lastest_ver)
        - python --version ; pip --version ; sw_vers; pip list

# dist: xenial
# python:
#   - '3.5'
#   - '3.6'
#   - '3.7'

addons:
  apt:
    packages:
      - pandoc
      
install:
  # - pip install pytest pytest-console-scripts
  # - pip install pytest-cov
  # - pip install coveralls
  - pip install -r requirements.txt
  - pip install -e ".[test]"
  - mboot
  
script:
  - py.test --cov=mboot tests/*
  
# after_success:
#   - coveralls
  
# before_deploy:
  # - pip install pypandoc

# deploy:
#   provider: pypi
#   user: "molejar"
#   password:
#     secure: Ar2cQYfCdTLIO76FpoEMHA+vDKS3qI4KhJSpRjDBOpg6NlG4t1lGhB2Iffsgeb5cc7CD+/KpyU0dDAEDPFePbi+sUlYdmWUFP8ounHCPiuxjZkKRfj0QK5WugIl34U37zKn9l5+WYjW1mLL0DR681UnGeY/+RwU88XmK8hrsBbKJIJS62S2ysn58eCPJMxC/6tD0iz9cPZGwk51N57+RzWLmvJsHUcBKimqAq1OPtcIAtZilyI25MxOxDDliv3LVksGliJib9jamTmPElgutLQ+9HGP32HEwZKdDeroJ3RwbVawt573WYZwl9mbDqxbNpznL8N49CI2tJ49NI5QQHSkzrTL9k99ggV/9jqTn+ZYC4mkQDuK+kizSDJ9BDYxT3b83a+DVhJMZXWFOQX2VZwJEuScncw9TwPmw670h/B3XFPdarkGKwbiu5KePsbO/s1mfw6Qw9LbM2dS2RBJ7Agyvq+gBPJ4UsZjpaaOcKH0W6SbT1ykwZsmk44LXG0mqSMmJxOfkAf6qdNTiLocO1edbQJ/Kanc/UcmHZjHOei0wmbIwc8lg8zdiRLy+NGqWok2kx/lM1h3Fe/XF5c4eW79QmiarJkudZaTbm2jMm/kwVMCSNTRvLQh2q41V9RjTFU1FHIajyH7aP3lvg6aEhQIIA/Xy/zMi5KbEzenGpOg=
#   distributions: "sdist bdist_wheel"
#   skip_existing: true
#   on:
#     tags: true
